title: My Website
description: My personal corner of the internet

collections:
  artwork:
    output: true
    permalink: /art/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: artwork
    values:
      layout: artwork